def checkException(title):
    if title == "The Elder Scrolls IV: Oblivion GOTY Edition": return "The Elder Scrolls IV"
    elif title == "DRAGON QUEST XI S: Echoes of an Elusive Age - Definitive Edition (ROW Edition)": return "DRAGON QUEST XI S: Echoes of an Elusive Age"
    elif title == "RESIDENT EVIL 2 / BIOHAZARD RE:2 Standard Edition": return "RESIDENT EVIL 2 BIOHAZARD RE:2"
    elif title == "CRISIS CORE -FINAL FANTASY- VII REUNION": return "CRISIS CORE FINAL FANTASY VII REUNION"
    elif title == "LEGO Star Wars: The Skywalker Saga Deluxe Edition": return "LEGO Star Wars: The Skywalker Saga"
    elif title == "DuckTales : Remastered": return "DuckTales: Remastered"
    elif title == "Ancestors: The Humankind Odyssey (STEAM)": return "Ancestors: The Humankind Odyssey"
    elif title == "Devil May Cry 4 - Special Edition": return "Devil May Cry 4 Special Edition"
    elif title == "NieR:Automata Game of the YoRHa Edition": return "NieR:Automata"
    elif title == "Cities: Skylines II - Pre-Order": return "Cities: Skylines II"
    elif title == "OKAMI HD / 大神 絶景版": return "OKAMI HD"
    elif title == "Demon Slayer -Kimetsu no Yaiba- The Hinokami Chronicles": return "Demon Slayer Kimetsu no Yaiba The Hinokami Chronicles"
    elif title == "Persona 5 Strikers - Deluxe Edition": return "Persona 5 Strikers"
    elif title == "Naruto Shippuden : Ultimate Ninja Storm 4": return "Naruto Shippuden: Ultimate Ninja Storm 4"
    elif title == "Monster Hunter Stories 2: Wings of Ruin Standard Edition": return "Monster Hunter Stories 2: Wings of Ruin"
    elif title == "The Council - Complete Season": return "The Council"
    elif title == "The Quarry - Deluxe Edition": return "The Quarry"
    elif title == "Like a Dragon: Ishin! - Digital Deluxe": return "Like a Dragon: Ishin!"
    elif title == "Space Hulk: Deathwing - Enhanced Edition": return "Space Hulk: Deathwing Enhanced Edition"
    elif title == "FINAL FANTASY VIII - REMASTERED": return "FINAL FANTASY VIII REMASTERED"
    elif title == "The Secret of Monkey Island : Special Edition": return "The Secret of Monkey Island: Special Edition"
    elif title == "Sonic Colors: Ultimate - Digital Deluxe": return "Sonic Colors: Ultimate"
    elif title == "Knights of Honor II - Sovereign": return "Knights of Honor II Sovereign"
    elif title == "Yakuza: Like a Dragon - Hero Edition": return "Yakuza: Like a Dragon"
    elif title == "Marvel's Midnight Suns Digital+ Edition": return "Marvel's Midnight Suns"
    else: return title